#! /bin/sh
bspc rule -r "*"

# Variables for sxhkdrc
sxhkd &

# picom
picom --experimental-backends &

# Variables for bspwmrc
border_color="#61AFEF"

bspc monitor -d 1 2 3 4 5 6 7 8 9 10

bspc config border_width         4
bspc config window_gap          8
bspc config top_padding         40

bspc config split_ratio          0.51
bspc config borderless_monocle   false
bspc config gapless_monocle      false
bspc config focus_follows_pointer       true
bspc config history_aware_focus         true # don't know

bspc config normal_border_color   "#484848"
bspc config focused_border_color  $border_color
bspc config urgent_border_color   "#484848"
bspc config presel_border_color   "#484848"

# movie and resize window with mouse
# bspc config pointer_modifier mod4
# bspc config pointer_action1 move
# bspc config pointer_action2 resize_side

# bspc config pointer_action2 resize_corner
# bspc config honor_size_hints true
# bspc config ignore_ewh_struts polybar

########################################################
############       BSPC RULE       #####################
########################################################

# Use monocle layout on desktop 1
# bspc desktop '^1' --layout monocle
# bspc rule -a Gimp desktop='^8' state=floating follow=on
# bspc rule -a Chromium desktop='^3'

bspc rule -a mplayer2 state=floating
# bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off

# Send to www desktop
bspc rule --add firefox        desktop='3' follow=on center=true state=floating
bspc rule --add Google-chrome  desktop='3' follow=on private=on rectangle=900x800+1000+50 state=floating
bspc rule --add Brave-browser desktop='3' follow=on rectangle=900x800+30+250 state=floating
bspc rule -a Messenger\ call\ -\ Brave rectangle=450x800+1400+50 state=floating
bspc rule -a Org.gnome.Nautilus desktop='4' follow=on rectangle=900x800+507+130 state=floating
bspc rule -a MongoDB\ Compass desktop='9' follow=on center=true state=floating
bspc rule -a Mysql-workbench-bin desktop='9' follow=on center=true state=floating
bspc rule -a Eclipse desktop='2' follow=on center=true state=floating
bspc rule -a Code desktop='1' follow=on center=true state=floating

# Random Picture Every Login
feh --bg-scale --randomize ~/.config/Arch\ Config/Anime/*

# fix X cursor to default
xsetroot -cursor_name left_ptr &

# Polybar
"$HOME/.config/polybar/launch.sh" &

